-- MySQL Script generated by MySQL Workbench
-- 01/28/17 21:32:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema armoredcars
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `armoredcars`;

CREATE SCHEMA IF NOT EXISTS `armoredcars`
  DEFAULT CHARACTER SET utf8;
USE `armoredcars`;

-- -----------------------------------------------------
-- Table `armoredcars`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `armoredcars`.`client`;

CREATE TABLE IF NOT EXISTS `armoredcars`.`client` (
  `ID`            INT(11)              NOT NULL AUTO_INCREMENT,
  `NAME`          VARCHAR(100)
                  CHARACTER SET 'utf8' NOT NULL,
  `DOCUMENT`      VARCHAR(100)
                  CHARACTER SET 'utf8' NULL     DEFAULT NULL,
  `DOCUMENT_TYPE` VARCHAR(10)
                  CHARACTER SET 'utf8' NOT NULL,
  `EMAIL`         VARCHAR(100)
                  CHARACTER SET 'utf8' NULL     DEFAULT NULL,
  `PHONE`         VARCHAR(100)
                  CHARACTER SET 'utf8' NULL     DEFAULT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 1
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_bin;

CREATE UNIQUE INDEX `CLIENT_UQ_CLIENT` ON client (`DOCUMENT` ASC, `DOCUMENT_TYPE` ASC);

CREATE INDEX `FK_CLIENT_DOCUMENT_TYPE` ON client (`DOCUMENT_TYPE` ASC);

INSERT INTO `armoredcars`.`client`
(`NAME`, `DOCUMENT`, `DOCUMENT_TYPE`)
VALUES
  ('GENERICO', '00000000', 'DNI');

-- -----------------------------------------------------
-- Table `armoredcars`.`billing_and_reference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `armoredcars`.`billing_and_reference`;

CREATE TABLE IF NOT EXISTS `armoredcars`.`billing_and_reference` (
  `ID`                INT(11)              NOT NULL AUTO_INCREMENT,
  `OWNER`             VARCHAR(100)
                      CHARACTER SET 'utf8' NULL     DEFAULT NULL,
  `CONTACT_PERSON`    VARCHAR(100)
                      CHARACTER SET 'utf8' NULL     DEFAULT NULL,
  `BILL_TO_CLIENT_ID` INT(11)              NULL     DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_BILLING_AND_REFERENCE_CLIENT`
  FOREIGN KEY (`BILL_TO_CLIENT_ID`)
  REFERENCES `armoredcars`.`client` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_bin;

CREATE INDEX `FK_BILLING_AND_REFERENCE_CLIENT` ON billing_and_reference (`BILL_TO_CLIENT_ID` ASC);

-- -----------------------------------------------------
-- Table `armoredcars`.`car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `armoredcars`.`car`;

CREATE TABLE IF NOT EXISTS `armoredcars`.`car` (
  `ID`             INT(11)              NOT NULL AUTO_INCREMENT,
  `BRAND`          VARCHAR(100)
                   CHARACTER SET 'utf8' NULL     DEFAULT NULL,
  `MODEL`          VARCHAR(100)
                   CHARACTER SET 'utf8' NULL     DEFAULT NULL,
  `CHASSIS_NUMBER` VARCHAR(100)
                   CHARACTER SET 'utf8' NULL     DEFAULT NULL,
  `MOTOR_NUMBER`   VARCHAR(100)
                   CHARACTER SET 'utf8' NULL     DEFAULT NULL,
  `DOMAIN`         VARCHAR(100)
                   CHARACTER SET 'utf8' NULL     DEFAULT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_bin;

-- -----------------------------------------------------
-- Table `armoredcars`.`armored`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `armoredcars`.`armored`;

CREATE TABLE IF NOT EXISTS `armoredcars`.`armored` (
  `ID`                       INT(11)              NOT NULL AUTO_INCREMENT,
  `ENTRY_DATE`               DATETIME             NULL     DEFAULT NULL,
  `DEPARTURE_DATE`           DATETIME             NULL     DEFAULT NULL,
  `DELIVERY_DATE`            DATETIME             NULL     DEFAULT NULL,
  `CAR_ID`                   INT(11)              NOT NULL,
  `BILLING_AND_REFERENCE_ID` INT(11)              NOT NULL,
  `CODE`                     INT(11)              NOT NULL,
  `PRICE`                    DECIMAL(18, 3)       NOT NULL DEFAULT '0.000',
  `STOCK_STATUS`             VARCHAR(50)
                             CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_ARMORED_BILLINGS_AND_REFERENCE`
  FOREIGN KEY (`BILLING_AND_REFERENCE_ID`)
  REFERENCES `armoredcars`.`billing_and_reference` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ARMORED_CAR`
  FOREIGN KEY (`CAR_ID`)
  REFERENCES `armoredcars`.`car` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_bin;

CREATE UNIQUE INDEX `ARMORED_UQ__ARMOREDS__00000000000000F2` ON armored (`CODE` ASC);

CREATE INDEX `FK_ARMORED_CAR` ON armored (`CAR_ID` ASC);

CREATE INDEX `FK_ARMORED_BILLINGS_AND_REFERENCE` ON armored (`BILLING_AND_REFERENCE_ID` ASC);

-- -----------------------------------------------------
-- Table `armoredcars`.`currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `armoredcars`.`currency`;

CREATE TABLE IF NOT EXISTS `armoredcars`.`currency` (
  `ID`          INT(11)              NOT NULL AUTO_INCREMENT,
  `CODE`        CHAR(3)
                CHARACTER SET 'utf8' NOT NULL,
  `DESCRIPTION` VARCHAR(100)
                CHARACTER SET 'utf8' NULL     DEFAULT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 1
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_bin;

CREATE UNIQUE INDEX `CURRENCY_UQ__CURRENCIES__0000000000000194` ON currency (`CODE` ASC);

INSERT INTO `armoredcars`.`currency`
(`CODE`, `DESCRIPTION`)
VALUES
  ('AED', 'United Arab Emirates Dirham'),
  ('AFN', 'Afghanistan Afghani'),
  ('ALL', 'Albania Lek'),
  ('AMD', 'Armenia Dram'),
  ('ANG', 'Netherlands Antilles Guilder'),
  ('AOA', 'Angola Kwanza'),
  ('ARS', 'Argentina Peso'),
  ('AUD', 'Australia Dollar'),
  ('AWG', 'Aruba Guilder'),
  ('AZN', 'Azerbaijan New Manat'),
  ('BAM', 'Bosnia and Herzegovina Convertible Marka'),
  ('BBD', 'Barbados Dollar'),
  ('BDT', 'Bangladesh Taka'),
  ('BGN', 'Bulgaria Lev'),
  ('BHD', 'Bahrain Dinar'),
  ('BIF', 'Burundi Franc'),
  ('BMD', 'Bermuda Dollar'),
  ('BND', 'Brunei Darussalam Dollar'),
  ('BOB', 'Bolivia Boliviano'),
  ('BRL', 'Brazil Real'),
  ('BSD', 'Bahamas Dollar'),
  ('BTN', 'Bhutan Ngultrum'),
  ('BWP', 'Botswana Pula'),
  ('BYR', 'Belarus Ruble'),
  ('BZD', 'Belize Dollar'),
  ('CAD', 'Canada Dollar'),
  ('CDF', 'Congo/Kinshasa Franc'),
  ('CHF', 'Switzerland Franc'),
  ('CLP', 'Chile Peso'),
  ('CNY', 'China Yuan Renminbi'),
  ('COP', 'Colombia Peso'),
  ('CRC', 'Costa Rica Colon'),
  ('CUC', 'Cuba Convertible Peso'),
  ('CUP', 'Cuba Peso'),
  ('CVE', 'Cape Verde Escudo'),
  ('CZK', 'Czech Republic Koruna'),
  ('DJF', 'Djibouti Franc'),
  ('DKK', 'Denmark Krone'),
  ('DOP', 'Dominican Republic Peso'),
  ('DZD', 'Algeria Dinar'),
  ('EGP', 'Egypt Pound'),
  ('ERN', 'Eritrea Nakfa'),
  ('ETB', 'Ethiopia Birr'),
  ('EUR', 'Euro Member Countries'),
  ('FJD', 'Fiji Dollar'),
  ('FKP', 'Falkland Islands (Malvinas) Pound'),
  ('GBP', 'United Kingdom Pound'),
  ('GEL', 'Georgia Lari'),
  ('GGP', 'Guernsey Pound'),
  ('GHS', 'Ghana Cedi'),
  ('GIP', 'Gibraltar Pound'),
  ('GMD', 'Gambia Dalasi'),
  ('GNF', 'Guinea Franc'),
  ('GTQ', 'Guatemala Quetzal'),
  ('GYD', 'Guyana Dollar'),
  ('HKD', 'Hong Kong Dollar'),
  ('HNL', 'Honduras Lempira'),
  ('HRK', 'Croatia Kuna'),
  ('HTG', 'Haiti Gourde'),
  ('HUF', 'Hungary Forint'),
  ('IDR', 'Indonesia Rupiah'),
  ('ILS', 'Israel Shekel'),
  ('IMP', 'Isle of Man Pound'),
  ('INR', 'India Rupee'),
  ('IQD', 'Iraq Dinar'),
  ('IRR', 'Iran Rial'),
  ('ISK', 'Iceland Krona'),
  ('JEP', 'Jersey Pound'),
  ('JMD', 'Jamaica Dollar'),
  ('JOD', 'Jordan Dinar'),
  ('JPY', 'Japan Yen'),
  ('KES', 'Kenya Shilling'),
  ('KGS', 'Kyrgyzstan Som'),
  ('KHR', 'Cambodia Riel'),
  ('KMF', 'Comoros Franc'),
  ('KPW', 'Korea (North) Won'),
  ('KRW', 'Korea (South) Won'),
  ('KWD', 'Kuwait Dinar'),
  ('KYD', 'Cayman Islands Dollar'),
  ('KZT', 'Kazakhstan Tenge'),
  ('LAK', 'Laos Kip'),
  ('LBP', 'Lebanon Pound'),
  ('LKR', 'Sri Lanka Rupee'),
  ('LRD', 'Liberia Dollar'),
  ('LSL', 'Lesotho Loti'),
  ('LYD', 'Libya Dinar'),
  ('MAD', 'Morocco Dirham'),
  ('MDL', 'Moldova Leu'),
  ('MGA', 'Madagascar Ariary'),
  ('MKD', 'Macedonia Denar'),
  ('MMK', 'Myanmar (Burma) Kyat'),
  ('MNT', 'Mongolia Tughrik'),
  ('MOP', 'Macau Pataca'),
  ('MRO', 'Mauritania Ouguiya'),
  ('MUR', 'Mauritius Rupee'),
  ('MVR', 'Maldives (Maldive Islands) Rufiyaa'),
  ('MWK', 'Malawi Kwacha'),
  ('MXN', 'Mexico Peso'),
  ('MYR', 'Malaysia Ringgit'),
  ('MZN', 'Mozambique Metical'),
  ('NAD', 'Namibia Dollar'),
  ('NGN', 'Nigeria Naira'),
  ('NIO', 'Nicaragua Cordoba'),
  ('NOK', 'Norway Krone'),
  ('NPR', 'Nepal Rupee'),
  ('NZD', 'New Zealand Dollar'),
  ('OMR', 'Oman Rial'),
  ('PAB', 'Panama Balboa'),
  ('PEN', 'Peru Nuevo Sol'),
  ('PGK', 'Papua New Guinea Kina'),
  ('PHP', 'Philippines Peso'),
  ('PKR', 'Pakistan Rupee'),
  ('PLN', 'Poland Zloty'),
  ('PYG', 'Paraguay Guarani'),
  ('QAR', 'Qatar Riyal'),
  ('RON', 'Romania New Leu'),
  ('RSD', 'Serbia Dinar'),
  ('RUB', 'Russia Ruble'),
  ('RWF', 'Rwanda Franc'),
  ('SAR', 'Saudi Arabia Riyal'),
  ('SBD', 'Solomon Islands Dollar'),
  ('SCR', 'Seychelles Rupee'),
  ('SDG', 'Sudan Pound'),
  ('SEK', 'Sweden Krona'),
  ('SGD', 'Singapore Dollar'),
  ('SHP', 'Saint Helena Pound'),
  ('SLL', 'Sierra Leone Leone'),
  ('SOS', 'Somalia Shilling'),
  ('SPL', 'Seborga Luigino'),
  ('SRD', 'Suriname Dollar'),
  ('STD', 'São Tomé and Príncipe Dobra'),
  ('SVC', 'El Salvador Colon'),
  ('SYP', 'Syria Pound'),
  ('SZL', 'Swaziland Lilangeni'),
  ('THB', 'Thailand Baht'),
  ('TJS', 'Tajikistan Somoni'),
  ('TMT', 'Turkmenistan Manat'),
  ('TND', 'Tunisia Dinar'),
  ('TOP', 'Tonga Pa''anga'),
  ('TRY', 'Turkey Lira'),
  ('TTD', 'Trinidad and Tobago Dollar'),
  ('TVD', 'Tuvalu Dollar'),
  ('TWD', 'Taiwan New Dollar'),
  ('TZS', 'Tanzania Shilling'),
  ('UAH', 'Ukraine Hryvnia'),
  ('UGX', 'Uganda Shilling'),
  ('USD', 'United States Dollar'),
  ('UYU', 'Uruguay Peso'),
  ('UZS', 'Uzbekistan Som'),
  ('VEF', 'Venezuela Bolivar'),
  ('VND', 'Viet Nam Dong'),
  ('VUV', 'Vanuatu Vatu'),
  ('WST', 'Samoa Tala'),
  ('XAF', 'Communauté Financière Africaine (BEAC) CFA Franc BEAC'),
  ('XCD', 'East Caribbean Dollar'),
  ('XDR', 'International Monetary Fund (IMF) Special Drawing Rights'),
  ('XOF', 'Communauté Financière Africaine (BCEAO) Franc'),
  ('XPF', 'Comptoirs Français du Pacifique (CFP) Franc'),
  ('YER', 'Yemen Rial'),
  ('ZAR', 'South Africa Rand'),
  ('ZMW', 'Zambia Kwacha'),
  ('ZWD', 'Zimbabwe Dollar');

-- -----------------------------------------------------
-- Table `armoredcars`.`additional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `armoredcars`.`additional`;

CREATE TABLE IF NOT EXISTS `armoredcars`.`additional` (
  `ID`          INT(11)              NOT NULL AUTO_INCREMENT,
  `DATE`        DATETIME             NOT NULL,
  `ARMORED_ID`  INT(11)              NOT NULL,
  `AMOUNT`      DECIMAL(18, 3)       NOT NULL,
  `CONVERSION`  DECIMAL(18, 9)       NOT NULL,
  `CURRENCY_ID` INT(11)              NOT NULL,
  `DESCRIPTION` VARCHAR(255)
                CHARACTER SET 'utf8' NULL     DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_ADDITIONAL_SPENDING_ARMORED`
  FOREIGN KEY (`ARMORED_ID`)
  REFERENCES `armoredcars`.`armored` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ADDITIONAL_SPENDING_CURRENCY`
  FOREIGN KEY (`CURRENCY_ID`)
  REFERENCES `armoredcars`.`currency` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_bin;

CREATE INDEX `FK_ADDITIONAL_SPENDING_ARMORED` ON additional (`ARMORED_ID` ASC);

CREATE INDEX `FK_ADDITIONAL_SPENDING_CURRENCY` ON additional (`CURRENCY_ID` ASC);

-- -----------------------------------------------------
-- Table `armoredcars`.`additional_collection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `armoredcars`.`additional_collection`;

CREATE TABLE IF NOT EXISTS `armoredcars`.`additional_collection` (
  `ID`            INT(11)              NOT NULL AUTO_INCREMENT,
  `AMOUNT`        DECIMAL(18, 3)       NOT NULL,
  `DATE`          DATETIME             NOT NULL,
  `ADDITIONAL_ID` INT(11)              NOT NULL,
  `DESCRIPTION`   VARCHAR(255)
                  CHARACTER SET 'utf8' NULL     DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_ADDITIONAL_SPENDING_COLLECTION_ADDITIONAL_SPENDING`
  FOREIGN KEY (`ADDITIONAL_ID`)
  REFERENCES `armoredcars`.`armored` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_bin;

CREATE INDEX `FK_ADDITIONAL_SPENDING_COLLECTION_ADDITIONAL_SPENDING` ON additional_collection (`ADDITIONAL_ID` ASC);

-- -----------------------------------------------------
-- Table `armoredcars`.`armored_excel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `armoredcars`.`armored_excel`;

CREATE TABLE IF NOT EXISTS `armoredcars`.`armored_excel` (
  `ID`          INT(11)  NOT NULL AUTO_INCREMENT,
  `LAST_UPDATE` DATETIME NOT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 1
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_bin;

INSERT INTO `armoredcars`.`armored_excel`
(`LAST_UPDATE`)
VALUES
  (NOW());

-- -----------------------------------------------------
-- Table `armoredcars`.`bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `armoredcars`.`bill`;

CREATE TABLE IF NOT EXISTS `armoredcars`.`bill` (
  `ID`                    INT(11)              NOT NULL     AUTO_INCREMENT,
  `DATE`                  DATETIME             NOT NULL,
  `ARMORED_ID`            INT(11)              NOT NULL,
  `CONVERSION`            DECIMAL(18, 9)       NOT NULL,
  `NUMBER`                BIGINT(20)           NOT NULL,
  `CURRENCY_ID`           INT(11)              NOT NULL,
  `BILL_TO_NAME`          VARCHAR(100)
                          CHARACTER SET 'utf8' NOT NULL,
  `BILL_TO_DOCUMENT`      VARCHAR(100)
                          CHARACTER SET 'utf8' NULL         DEFAULT NULL,
  `BILL_TO_DOCUMENT_TYPE` VARCHAR(10)
                          CHARACTER SET 'utf8' NOT NULL,
  `ALIQUOT`               DECIMAL(18, 2)       NOT NULL     DEFAULT '0.00',
  `TAXED_AMOUNT`          DECIMAL(18, 3)       NOT NULL     DEFAULT '0.000',
  `UNTAXED_AMOUNT`        DECIMAL(18, 3)       NOT NULL     DEFAULT '0.000',
  `BILL_TYPE_CODE`        VARCHAR(100)
                          CHARACTER SET 'utf8' NOT NULL,
  `VAT_AMOUNT`            DECIMAL(18, 3)       NOT NULL     DEFAULT '0.000',
  `TOTAL_AMOUNT`          DECIMAL(18, 3)       NOT NULL     DEFAULT '0.000',
  `APPLY_BILL_ID`         INT(11)              NULL         DEFAULT NULL,
  `DESCRIPTION`           VARCHAR(255)
                          CHARACTER SET 'utf8' NULL         DEFAULT NULL,
  `BILL_TO_ID`            INT(11)              NULL         DEFAULT NULL,
  `FINANCIAL_ADVANCE`     BIT                  NOT NULL     DEFAULT 0,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_BILL_APPLY_BILL`
  FOREIGN KEY (`APPLY_BILL_ID`)
  REFERENCES `armoredcars`.`bill` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BILL_ARMORED`
  FOREIGN KEY (`ARMORED_ID`)
  REFERENCES `armoredcars`.`armored` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BILL_CLIENT`
  FOREIGN KEY (`BILL_TO_ID`)
  REFERENCES `armoredcars`.`client` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BILL_CURRENCY`
  FOREIGN KEY (`CURRENCY_ID`)
  REFERENCES `armoredcars`.`currency` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_bin;

CREATE UNIQUE INDEX `BILL_UQ_BILL` ON bill (`NUMBER` ASC, `BILL_TYPE_CODE` ASC);

CREATE INDEX `FK_BILL_APPLY_BILL` ON bill (`APPLY_BILL_ID` ASC);

CREATE INDEX `FK_BILL_CLIENT` ON bill (`BILL_TO_ID` ASC);

CREATE INDEX `FK_BILL_CURRENCY` ON bill (`CURRENCY_ID` ASC);

CREATE INDEX `FK_BILL_DOCUMENT_TYPE` ON bill (`BILL_TO_DOCUMENT_TYPE` ASC);

CREATE INDEX `FK_BILL_ARMORED` ON bill (`ARMORED_ID` ASC);

-- -----------------------------------------------------
-- Table `armoredcars`.`collection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `armoredcars`.`collection`;

CREATE TABLE IF NOT EXISTS `armoredcars`.`collection` (
  `ID`           INT(11)              NOT NULL AUTO_INCREMENT,
  `BILL_ID`      INT(11)              NULL     DEFAULT NULL,
  `BASE_AMOUNT`  DECIMAL(18, 3)       NOT NULL,
  `IIBB_AMOUNT`  DECIMAL(18, 3)       NOT NULL,
  `SUSS_AMOUNT`  DECIMAL(18, 3)       NOT NULL,
  `GAIN_AMOUNT`  DECIMAL(18, 3)       NOT NULL,
  `VAT_AMOUNT`   DECIMAL(18, 3)       NOT NULL,
  `DATE`         DATETIME             NOT NULL,
  `TOTAL_AMOUNT` DECIMAL(18, 3)       NOT NULL,
  `DESCRIPTION`  VARCHAR(25)
                 CHARACTER SET 'utf8' NULL     DEFAULT NULL,
  `CLIENT_ID`    INT(11)              NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_COLLECTION_CLIENT`
  FOREIGN KEY (`CLIENT_ID`)
  REFERENCES `armoredcars`.`client` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_bin;

CREATE INDEX `FK_COLLECTION_CLIENT` ON collection (`CLIENT_ID` ASC);

-- -----------------------------------------------------
-- Table `armoredcars`.`commission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `armoredcars`.`commission`;

CREATE TABLE IF NOT EXISTS `armoredcars`.`commission` (
  `ID`          INT(11)              NOT NULL AUTO_INCREMENT,
  `AMOUNT`      DECIMAL(18, 3)       NOT NULL,
  `PERSON`      VARCHAR(100)
                CHARACTER SET 'utf8' NOT NULL,
  `CONVERSION`  DECIMAL(18, 9)       NOT NULL,
  `CURRENCY_ID` INT(11)              NOT NULL,
  `DATE`        DATETIME             NOT NULL,
  `ARMORED_ID`  INT(11)              NOT NULL,
  `DESCRIPTION` VARCHAR(255)
                CHARACTER SET 'utf8' NULL     DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_COMMISSION_ARMORED`
  FOREIGN KEY (`ARMORED_ID`)
  REFERENCES `armoredcars`.`armored` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_COMMISSION_CURRENCY`
  FOREIGN KEY (`CURRENCY_ID`)
  REFERENCES `armoredcars`.`currency` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_bin;

CREATE INDEX `FK_COMMISSION_CURRENCY` ON commission (`CURRENCY_ID` ASC);

CREATE INDEX `FK_COMMISSION_ARMORED` ON commission (`ARMORED_ID` ASC);

-- -----------------------------------------------------
-- Table `armoredcars`.`commission_payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `armoredcars`.`commission_payment`;

CREATE TABLE IF NOT EXISTS `armoredcars`.`commission_payment` (
  `ID`            INT(11)              NOT NULL AUTO_INCREMENT,
  `AMOUNT`        DECIMAL(18, 3)       NOT NULL,
  `DATE`          DATETIME             NOT NULL,
  `COMMISSION_ID` INT(11)              NOT NULL,
  `DESCRIPTION`   VARCHAR(255)
                  CHARACTER SET 'utf8' NULL     DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_COMMISSION_PAYMENT_COMMISSION`
  FOREIGN KEY (`COMMISSION_ID`)
  REFERENCES `armoredcars`.`commission` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_bin;

CREATE INDEX `FK_COMMISSION_PAYMENT_COMMISSION` ON commission_payment (`COMMISSION_ID` ASC);

-- -----------------------------------------------------
-- Table `armoredcars`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `armoredcars`.`user`;

CREATE TABLE IF NOT EXISTS `armoredcars`.`user` (
  `ID`         INT(11)              NOT NULL AUTO_INCREMENT,
  `USER`       VARCHAR(100)
               CHARACTER SET 'utf8' NOT NULL,
  `PASSWORD`   VARCHAR(66)
               CHARACTER SET 'utf8' NOT NULL,
  `USER_LEVEL` VARCHAR(100)
               CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 1
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_bin;

CREATE UNIQUE INDEX `USER_UQ__USERS__000000000000009A` ON user (`USER` ASC);

INSERT INTO `armoredcars`.`user`
(`USER`, `PASSWORD`, `USER_LEVEL`)
VALUES
  ('admin', '21232f297a57a5a743894a0e4a801fc3', 'FINANCIAL');


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;